# Say "hello world" using podman

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install podman
      run: |
        sudo apt-get install podman
        
    - name: Run a command
      run: |
        podman run docker.io/library/ubuntu:latest /bin/echo "Hello World"

