# Say "hello world" using podman

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Install podman
      run: |
        sudo apt-get install podman
        
    - name: Run a command in a container
      run: |
        podman run docker.io/library/ubuntu:latest /bin/echo "Hello World"

    - name: Run the command again without the initial download
      run: |
        podman run docker.io/library/ubuntu:latest /bin/echo "Hello World2"

    - name: See installed ccommands
      run: |
        podman run docker.io/library/ubuntu:latest /bin/ls -la /usr/bin

    - name: Run perl
      run: |
        podman run docker.io/library/ubuntu:latest /usr/bin/perl -e"printf \"Hello Word from Perl\";"

